# Generated by Django 4.0.5 on 2022-06-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_user_repass_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='repass',
        ),
    ]
