# Generated by Django 4.0.5 on 2022-06-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_remove_user_repass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='repassword',
            field=models.TextField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=60),
        ),
    ]
