# Generated by Django 4.0.5 on 2022-06-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_user_repassword_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
