# Generated by Django 4.0.5 on 2022-06-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='discription',
            field=models.TextField(max_length=100),
        ),
    ]
