# Generated by Django 4.1.6 on 2023-10-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_alter_todo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='discription',
            new_name='description',
        ),
    ]
