on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone pr-agent repository
        run: git clone https://github.com/sarbjitsinghgrewal/pr-agent.git

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start Docker containers
        run: |
          cd pr-agent
          docker-compose up --build -d

      - name: list of folder
        run: ls

    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

