on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone pr-agent repository
        run: git clone https://github.com/sarbjitsinghgrewal/pr-agent.git

      - name: Inside pr-agent dir
        run: cd pr-agent
      
      - name: List files in the directory
        run: ls


    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

